# SPDX-FileCopyrightText: 2023 CERN.
# SPDX-License-Identifier: MIT

extends:
  - '@inveniosoftware/eslint-config-invenio/configs/react18.yaml'
  - '@inveniosoftware/eslint-config-invenio/prettier'

rules:
  react/default-props-match-prop-types: off
