# -*- coding: utf-8 -*-
#
# This file is part of Invenio-RDM-Records.
# Copyright (C) 2023 CERN.
#
# Invenio is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

extends:
  - '@inveniosoftware/eslint-config-invenio'
  - '@inveniosoftware/eslint-config-invenio/prettier'

rules:
  react/default-props-match-prop-types: off
