#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Column defaults and files indices."""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import invenio_db.shared
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1777278349'
down_revision = '1777274324'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uidx_rdm_drafts_files_id_key'), table_name='rdm_drafts_files')
    op.create_index(op.f('ix_rdm_drafts_files_record_id'), 'rdm_drafts_files', ['record_id'], unique=False)
    op.create_index('uidx_rdm_drafts_files_record_id_key', 'rdm_drafts_files', ['record_id', 'key'], unique=True)
    op.drop_index(op.f('uidx_rdm_drafts_media_files_id_key'), table_name='rdm_drafts_media_files')
    op.create_index(op.f('ix_rdm_drafts_media_files_record_id'), 'rdm_drafts_media_files', ['record_id'], unique=False)
    op.create_index('uidx_rdm_drafts_media_files_record_id_key', 'rdm_drafts_media_files', ['record_id', 'key'], unique=True)
    op.drop_index(op.f('uidx_rdm_records_files_id_key'), table_name='rdm_records_files')
    op.create_index(op.f('ix_rdm_records_files_record_id'), 'rdm_records_files', ['record_id'], unique=False)
    op.create_index('uidx_rdm_records_files_record_id_key', 'rdm_records_files', ['record_id', 'key'], unique=True)
    op.alter_column('rdm_records_files_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('rdm_records_files_version', 'created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               autoincrement=False)
    op.alter_column('rdm_records_files_version', 'updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               autoincrement=False)
    op.alter_column('rdm_records_files_version', 'key',
               existing_type=sa.TEXT(),
               nullable=True,
               autoincrement=False)
    op.alter_column('rdm_records_files_version', 'record_id',
               existing_type=sa.UUID(),
               nullable=True,
               autoincrement=False)
    op.create_index(op.f('ix_rdm_records_files_version_record_id'), 'rdm_records_files_version', ['record_id'], unique=False)
    op.drop_index(op.f('uidx_rdm_records_media_files_id_key'), table_name='rdm_records_media_files')
    op.create_index(op.f('ix_rdm_records_media_files_record_id'), 'rdm_records_media_files', ['record_id'], unique=False)
    op.create_index('uidx_rdm_records_media_files_record_id_key', 'rdm_records_media_files', ['record_id', 'key'], unique=True)
    op.alter_column('rdm_records_media_files_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=False)
    op.alter_column('rdm_records_media_files_version', 'created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               autoincrement=False)
    op.alter_column('rdm_records_media_files_version', 'updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               autoincrement=False)
    op.alter_column('rdm_records_media_files_version', 'key',
               existing_type=sa.TEXT(),
               nullable=True,
               autoincrement=False)
    op.alter_column('rdm_records_media_files_version', 'record_id',
               existing_type=sa.UUID(),
               nullable=True,
               autoincrement=False)
    op.create_index(op.f('ix_rdm_records_media_files_version_record_id'), 'rdm_records_media_files_version', ['record_id'], unique=False)
    op.create_index(op.f('ix_rdm_records_quota_user_id'), 'rdm_records_quota', ['user_id'], unique=False)
    op.alter_column('rdm_records_secret_links', 'origin',
               existing_type=sa.VARCHAR(length=255),
               server_default=None,
               existing_nullable=False)
    op.alter_column('rdm_records_secret_links', 'description',
               existing_type=sa.TEXT(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rdm_records_secret_links', 'description',
               existing_type=sa.TEXT(),
               server_default=sa.text("''::text"),
               existing_nullable=False)
    op.alter_column('rdm_records_secret_links', 'origin',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("''::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_rdm_records_quota_user_id'), table_name='rdm_records_quota')
    op.drop_index(op.f('ix_rdm_records_media_files_version_record_id'), table_name='rdm_records_media_files_version')
    op.alter_column('rdm_records_media_files_version', 'record_id',
               existing_type=sa.UUID(),
               nullable=False,
               autoincrement=False)
    op.alter_column('rdm_records_media_files_version', 'key',
               existing_type=sa.TEXT(),
               nullable=False,
               autoincrement=False)
    op.alter_column('rdm_records_media_files_version', 'updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               autoincrement=False)
    op.alter_column('rdm_records_media_files_version', 'created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               autoincrement=False)
    op.alter_column('rdm_records_media_files_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.drop_index('uidx_rdm_records_media_files_record_id_key', table_name='rdm_records_media_files')
    op.drop_index(op.f('ix_rdm_records_media_files_record_id'), table_name='rdm_records_media_files')
    op.create_index(op.f('uidx_rdm_records_media_files_id_key'), 'rdm_records_media_files', ['id', 'key'], unique=True)
    op.drop_index(op.f('ix_rdm_records_files_version_record_id'), table_name='rdm_records_files_version')
    op.alter_column('rdm_records_files_version', 'record_id',
               existing_type=sa.UUID(),
               nullable=False,
               autoincrement=False)
    op.alter_column('rdm_records_files_version', 'key',
               existing_type=sa.TEXT(),
               nullable=False,
               autoincrement=False)
    op.alter_column('rdm_records_files_version', 'updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               autoincrement=False)
    op.alter_column('rdm_records_files_version', 'created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               autoincrement=False)
    op.alter_column('rdm_records_files_version', 'version_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=False)
    op.drop_index('uidx_rdm_records_files_record_id_key', table_name='rdm_records_files')
    op.drop_index(op.f('ix_rdm_records_files_record_id'), table_name='rdm_records_files')
    op.create_index(op.f('uidx_rdm_records_files_id_key'), 'rdm_records_files', ['id', 'key'], unique=True)
    op.drop_index('uidx_rdm_drafts_media_files_record_id_key', table_name='rdm_drafts_media_files')
    op.drop_index(op.f('ix_rdm_drafts_media_files_record_id'), table_name='rdm_drafts_media_files')
    op.create_index(op.f('uidx_rdm_drafts_media_files_id_key'), 'rdm_drafts_media_files', ['id', 'key'], unique=True)
    op.drop_index('uidx_rdm_drafts_files_record_id_key', table_name='rdm_drafts_files')
    op.drop_index(op.f('ix_rdm_drafts_files_record_id'), table_name='rdm_drafts_files')
    op.create_index(op.f('uidx_rdm_drafts_files_id_key'), 'rdm_drafts_files', ['id', 'key'], unique=True)
    # ### end Alembic commands ###
