#
# This file is part of Invenio.
# Copyright (C) 2026 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Create record_id index in rdm_parents_community."""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "1780576627"
down_revision = "1777278349"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_rdm_parents_community_record_id",
        "rdm_parents_community",
        ["record_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_rdm_parents_community_record_id",
        table_name="rdm_parents_community",
    )
    # ### end Alembic commands ###
